# Generated by Django 5.0.7 on 2024-07-29 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_icon',
            field=models.ImageField(default=1, upload_to='category_icon/'),
            preserve_default=False,
        ),
    ]
