# Generated by Django 5.0.7 on 2024-07-29 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0004_category_category_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=56, verbose_name='Название объявления')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('mileage', models.IntegerField(verbose_name='Пробег (км.)')),
                ('model', models.CharField(max_length=70, verbose_name='Модель')),
                ('state', models.CharField(choices=[('б/у', 'Б/у'), ('новый', 'Новый')], max_length=5, verbose_name='Состояние')),
                ('fuel', models.JSONField(default=list, verbose_name='Топливо')),
                ('kuzov', models.CharField(choices=[('бус', 'Бус'), ('внедорожник', 'Внедорожник'), ('кабриолет', 'Кабриолет'), ('кроссовер', 'Кроссовер'), ('купе', 'Купе'), ('лимузин', 'Лимузин'), ('минивэн', 'Минивэн'), ('пикап', 'Пикап'), ('седан', 'Седан'), ('универсал', 'Универсал'), ('фургон', 'Фургон'), ('хэтчбэк', 'Хэтчбэк')], max_length=70, verbose_name='Кузов')),
                ('transmission', models.JSONField(default=list, verbose_name='Коробка передач')),
                ('steering_wheel', models.CharField(choices=[('слева', 'Слева'), ('справа', 'Справа')], max_length=6, verbose_name='Руль')),
                ('drive_unit', models.CharField(choices=[('4WD, полный', '4WD, полный'), ('AWD, полный', 'AWD, полный'), ('задний', 'Задний'), ('передний', 'Передний')], max_length=20, verbose_name='Привод')),
                ('color', models.CharField(choices=[('красный', 'Красный'), ('синий', 'Синий'), ('зелёный', 'Зелёный'), ('чёрный', 'Чёрный'), ('белый', 'Белый'), ('серебристый', 'Серебристый'), ('жёлтый', 'Жёлтый')], max_length=12, verbose_name='Цвет')),
                ('engine_volume', models.CharField(choices=[('0.1', '0.1'), ('0.2', '0.2'), ('0.3', '0.3'), ('0.4', '0.4'), ('0.5', '0.5'), ('0.6', '0.6'), ('0.7', '0.7'), ('0.8', '0.8'), ('0.9', '0.9'), ('1.0', '1.0'), ('1.1', '1.1'), ('1.2', '1.2'), ('1.3', '1.3'), ('1.4', '1.4'), ('1.5', '1.5'), ('1.6', '1.6'), ('1.7', '1.7'), ('1.8', '1.8'), ('1.9', '1.9'), ('2.0', '2.0'), ('2.1', '2.1'), ('2.2', '2.2'), ('2.3', '2.3'), ('2.4', '2.4'), ('2.5', '2.5'), ('2.6', '2.6'), ('2.7', '2.7'), ('2.8', '2.8'), ('2.9', '2.9'), ('3.0', '3.0'), ('3.1', '3.1'), ('3.2', '3.2'), ('3.3', '3.3'), ('3.4', '3.4'), ('3.5', '3.5'), ('3.6', '3.6'), ('3.7', '3.7'), ('3.8', '3.8'), ('3.9', '3.9'), ('4.0', '4.0'), ('4.1', '4.1'), ('4.2', '4.2'), ('4.3', '4.3'), ('4.4', '4.4'), ('4.5', '4.5'), ('4.6', '4.6'), ('4.7', '4.7'), ('4.8', '4.8'), ('4.9', '4.9'), ('5.0', '5.0'), ('5.1', '5.1'), ('5.2', '5.2'), ('5.3', '5.3'), ('5.4', '5.4'), ('5.5', '5.5'), ('5.6', '5.6'), ('5.7', '5.7'), ('5.8', '5.8'), ('5.9', '5.9'), ('6.0', '6.0'), ('6.1', '6.1'), ('6.2', '6.2'), ('6.3', '6.3'), ('6.4', '6.4'), ('6.5', '6.5'), ('6.6', '6.6'), ('6.7', '6.7'), ('6.8', '6.8'), ('6.9', '6.9'), ('7.0', '7.0'), ('7.1', '7.1'), ('7.2', '7.2'), ('7.3', '7.3'), ('7.4', '7.4'), ('7.5', '7.5'), ('7.6', '7.6'), ('7.7', '7.7'), ('7.8', '7.8'), ('7.9', '7.9'), ('8.0', '8.0'), ('8.1', '8.1'), ('8.2', '8.2'), ('8.3', '8.3'), ('8.4', '8.4'), ('8.5', '8.5'), ('8.6', '8.6'), ('8.7', '8.7'), ('8.8', '8.8'), ('8.9', '8.9'), ('9.0', '9.0'), ('9.1', '9.1'), ('9.2', '9.2'), ('9.3', '9.3'), ('9.4', '9.4'), ('9.5', '9.5'), ('9.6', '9.6'), ('9.7', '9.7'), ('9.8', '9.8'), ('9.9', '9.9'), ('10.0', '10.0')], max_length=4, verbose_name='Объем двигателя')),
                ('VIN_code', models.CharField(choices=[('с VIN кодом', 'С VIN кодом'), ('без VIN кода', 'Без VIN кода')], max_length=14, verbose_name='VIN код')),
                ('technical_condition', models.JSONField(default=list, verbose_name='Техническое состояние')),
                ('customs_clearance', models.CharField(choices=[('не растаможен', 'Не растаможен'), ('растаможен', 'Растаможен')], max_length=14, verbose_name='Растаможка')),
                ('calculation', models.JSONField(default=list, verbose_name='Расчет')),
                ('availability', models.CharField(choices=[('на заказ', 'На заказ'), ('в наличии', 'В наличии')], max_length=14, verbose_name='Наличие')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('phone_numbers', models.JSONField(default=list)),
                ('car_images', models.JSONField(default=list)),
            ],
        ),
    ]
